name: asgard_env
channels:
  - conda-forge
dependencies:
  - python=3.11.6
  - r-base=4.3.1
  - r-essentials=4.3
  - r-here=1.0.1
  - rpy2=3.5.11
  - r-devtools=2.4.5
  - bioconductor-cmapr=1.12.0
  - bioconductor-biocfilecache=2.8.0
  # vscode related
  - r-languageserver=0.3.16
  - radian=0.6.7
  - r-httpgd=1.3.1